### PR TITLE
Top 10 words

### PR DESCRIPTION
**Pull request by iharshit009**
This is the text file containing the top 10 words with their frequencies.

### CODE REVIEW

**Comment by iharshit009** [comment]
is it now also incorrect??

**Comment by iharshit009** [comment]
I couldn't get whether my PR is in wrong place or what is the problem??
My repo is not getting merged??
Sir please guide me as I have contributed to it first time...

**Comment by iharshit009** [comment]
Sir is there any mistakes in my PR??

**Comment by svp19** [comment]
@iharshit009  Do tag a person if you don't get a response after some time :)...it's easy to lose track in the vast octoverse. @Sedherthe shall get back to u

**Comment by iharshit009** [comment]
Sorry sir I will take care next time.

**Comment by Sedherthe** [comment]
@iharshit009  Your solution exactly matches with mine!! 😄 
I would like to request a small change in the output here, as I mentioned in your previous PR  your output doesn't follow the format given in the question. Please check it and submit your solution again.... I shall merge it! 😃 
@svp19 Thanks for letting me know !👍  😄

**Comment by iharshit009** [comment]
I am working on this one.
I could not get about the format specified ...
I have created a text file with top 10 frequent words with their frequencies...
should I add it again..?

**Comment by Sedherthe** [comment]
@iharshit009  The output format which I wanted was -
**word: frequency**
You answer is absolutely correct :) But I wanted changes in the output format. It's okay now, not a big problem, since it's too late just let me know if you want to make the changes or whether I should merge it.

**Comment by iharshit009** [comment]
Sir actually the code which I have written is taking the index values of
those words and I could not solve the problem of removing those so should I
upload the code on ??

**Pull request merged**
