### PR TITLE
File that contains top 10 common words.

### PR DESCRIPTION
**Pull request by iharshit009**

### CODE REVIEW

**Comment by iharshit009** [comment]
This is file for top ten common words excluding the stop-words.

**Comment by Sedherthe** [comment]
Changes*

**Comment by Sedherthe** [comment]
Hey @iharshit009  Currently you have deleted all the changes you have made I guess ... Please check.

**Comment by Sedherthe** [comment]
Hey @iharshit009  Currently you have deleted all the changes you have made I guess ... Please check.

**Comment by Sedherthe** [comment]
Hey @iharshit009  Currently you have deleted all the changes you have made I guess ... Please check.

**Comment by Sedherthe** [comment]
Hey @iharshit009 Currently you have deleted all the changes you have made I guess ... Please check

**Comment by iharshit009** [comment]
yes i have made all the possible changes..

**Comment by Sedherthe** [comment]
@iharshit009 you have deleted all the changes you made ...so currently there are no changes in the file .
Please add the changes again and update the PR.

**Comment by Sedherthe** [comment]
Hey @iharshit009 !! 😄 
Please work on any one Pull Request . I would be easy for us to track and also avoid any confusion in case.
Let me know which one you are onto now and I shall close the other one.

**Comment by iharshit009** [comment]
please close this one I am working on the other one

**Pull request closed without merging**
